window.WriterDocx=(()=>{
  const enc=new TextEncoder(),dec=new TextDecoder(),crcTable=[];
  for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}
  const crc32=data=>{let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0};
  const u16=(v,a,o)=>{a[o]=v&255;a[o+1]=(v>>>8)&255},u32=(v,a,o)=>{u16(v,a,o);u16(v>>>16,a,o+2)};
  const concat=parts=>{const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out};
  function zip(files){const locals=[],centrals=[];let offset=0;for(const [name,value] of Object.entries(files)){const nm=enc.encode(name),data=typeof value==='string'?enc.encode(value):value,crc=crc32(data),h=new Uint8Array(30+nm.length);u32(0x04034b50,h,0);u16(20,h,4);u32(crc,h,14);u32(data.length,h,18);u32(data.length,h,22);u16(nm.length,h,26);h.set(nm,30);locals.push(h,data);const c=new Uint8Array(46+nm.length);u32(0x02014b50,c,0);u16(20,c,4);u16(20,c,6);u32(crc,c,16);u32(data.length,c,20);u32(data.length,c,24);u16(nm.length,c,28);u32(offset,c,42);c.set(nm,46);centrals.push(c);offset+=h.length+data.length}const central=concat(centrals),end=new Uint8Array(22);u32(0x06054b50,end,0);u16(centrals.length,end,8);u16(centrals.length,end,10);u32(central.length,end,12);u32(offset,end,16);return new Blob([...locals,central,end],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}
  const xe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
  function runs(node){if(node.nodeType===3)return node.nodeValue?'<w:r><w:t xml:space="preserve">'+xe(node.nodeValue)+'</w:t></w:r>':'';if(node.nodeType!==1)return '';if(node.tagName==='BR')return '<w:r><w:br/></w:r>';const style=[];if(node.matches('strong,b'))style.push('<w:b/>');if(node.matches('em,i'))style.push('<w:i/>');if(node.matches('u'))style.push('<w:u w:val="single"/>');if(node.matches('s,strike'))style.push('<w:strike/>');let inner=[...node.childNodes].map(runs).join('');return style.length?inner.replaceAll('<w:r>','<w:r><w:rPr>'+style.join('')+'</w:rPr>'):inner}
  function documentXml(html){const doc=new DOMParser().parseFromString('<body>'+html+'</body>','text/html'),paras=[];const add=(el,listType)=>{const tag=el.tagName||'P',props=[];if(/^H[1-3]$/.test(tag))props.push('<w:pStyle w:val="Heading'+tag[1]+'"/>');if(tag==='BLOCKQUOTE')props.push('<w:ind w:left="720"/>');if(listType)props.push('<w:numPr><w:ilvl w:val="0"/><w:numId w:val="'+(listType==='ol'?2:1)+'"/></w:numPr>');paras.push('<w:p>'+(props.length?'<w:pPr>'+props.join('')+'</w:pPr>':'')+[...el.childNodes].map(runs).join('')+'</w:p>')};for(const el of [...doc.body.children]){if(el.matches('ul,ol'))for(const li of el.children)add(li,el.tagName.toLowerCase());else add(el)}return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+paras.join('')+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'}
  function exportDocx(html){return zip({
    '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/></Types>',
    '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
    'word/document.xml':documentXml(html),
    'word/styles.xml':'<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:qFormat/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:qFormat/><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:style></w:styles>',
    'word/numbering.xml':'<?xml version="1.0" encoding="UTF-8"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:numFmt w:val="bullet"/><w:lvlText w:val="•"/></w:lvl></w:abstractNum><w:abstractNum w:abstractNumId="1"><w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num><w:num w:numId="2"><w:abstractNumId w:val="1"/></w:num></w:numbering>',
    'word/_rels/document.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/></Relationships>'
  })}
  const read16=(v,o)=>v.getUint16(o,true),read32=(v,o)=>v.getUint32(o,true);
  async function unzipEntry(buffer,wanted){const bytes=new Uint8Array(buffer),view=new DataView(buffer);let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(read32(view,i)===0x06054b50){end=i;break}if(end<0)throw new Error('Invalid DOCX package');let p=read32(view,end+16),count=read16(view,end+10);for(let i=0;i<count;i++){if(read32(view,p)!==0x02014b50)throw new Error('Invalid DOCX directory');const method=read16(view,p+10),size=read32(view,p+20),nameLen=read16(view,p+28),extra=read16(view,p+30),comment=read16(view,p+32),offset=read32(view,p+42),name=dec.decode(bytes.slice(p+46,p+46+nameLen));if(name===wanted){const localName=read16(view,offset+26),localExtra=read16(view,offset+28),start=offset+30+localName+localExtra,data=bytes.slice(start,start+size);if(method===0)return data;if(method===8&&typeof DecompressionStream!=='undefined'){const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(stream).arrayBuffer())}throw new Error('This browser cannot decompress this DOCX file')}p+=46+nameLen+extra+comment}throw new Error('DOCX document content was not found')}
  const descendants=(el,name)=>[...el.getElementsByTagNameNS('*',name)];
  function runHtml(r){const text=descendants(r,'t').map(x=>x.textContent).join(''),br=descendants(r,'br').length,p=descendants(r,'rPr')[0],open=[],close=[];if(p&&descendants(p,'b').length){open.push('<strong>');close.unshift('</strong>')}if(p&&descendants(p,'i').length){open.push('<em>');close.unshift('</em>')}if(p&&descendants(p,'u').length){open.push('<u>');close.unshift('</u>')}if(p&&descendants(p,'strike').length){open.push('<s>');close.unshift('</s>')}return open.join('')+xe(text)+(br?'<br>'.repeat(br):'')+close.join('')}
  async function importDocx(buffer){const xml=dec.decode(await unzipEntry(buffer,'word/document.xml')),doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('The DOCX XML is invalid');const out=[];let list=null;for(const p of descendants(doc,'p')){if(p.parentElement&&p.parentElement.localName==='txbxContent')continue;const styleNode=descendants(p,'pStyle')[0],style=styleNode?(styleNode.getAttribute('w:val')||styleNode.getAttribute('val')||''):'',isList=descendants(p,'numPr').length>0,tag=/Heading1/i.test(style)?'h1':/Heading2/i.test(style)?'h2':/Heading3/i.test(style)?'h3':'p',content=descendants(p,'r').map(runHtml).join('')||'<br>';if(isList){if(!list){list=[];out.push(list)}list.push(content)}else{list=null;out.push('<'+tag+'>'+content+'</'+tag+'>')}}return out.map(x=>Array.isArray(x)?'<ul>'+x.map(y=>'<li>'+y+'</li>').join('')+'</ul>':x).join('')}
  return {exportDocx,importDocx};
})();
