window.WriterTemplates=[
  {id:'blank',name:'Blank document',description:'A clean page for any purpose.',title:'Untitled document',html:'<p><br></p>'},
  {id:'letter',name:'Professional letter',description:'A clear formal letter layout.',title:'Professional letter',html:'<p>[Your name]<br>[Address]<br>[Email] · [Phone]</p><p>[Date]</p><p>[Recipient name]<br>[Company]<br>[Address]</p><p>Dear [Name],</p><p>Write your message here. Keep the purpose clear in the opening paragraph.</p><p>Use this paragraph for the relevant detail, evidence or requested next step.</p><p>Sincerely,</p><p>[Your name]</p>'},
  {id:'resume',name:'Resume / CV',description:'A simple ATS-friendly starting point.',title:'Resume – Your Name',html:'<h1>Your Name</h1><p>City · email@example.com · +00 000 000 000 · LinkedIn</p><h2>Professional profile</h2><p>Write a focused two-to-three sentence summary of your experience and value.</p><h2>Experience</h2><h3>Job title — Company</h3><p>Month Year – Month Year</p><ul><li>Describe an action, the context and a measurable result.</li><li>Add another relevant achievement.</li></ul><h2>Education</h2><h3>Qualification — Institution</h3><p>Year</p><h2>Skills</h2><p>Relevant skill · Relevant skill · Relevant skill</p>'},
  {id:'cover',name:'Cover letter',description:'A concise job-specific application.',title:'Cover letter',html:'<p>Dear [Hiring manager],</p><p>I am applying for [role] because [specific reason connected to the company or work].</p><p>In my role at [company], I [specific action and result]. This is relevant because [connection to the new role].</p><p>I would welcome the opportunity to discuss how my experience can support [team or goal].</p><p>Kind regards,<br>[Your name]</p>'},
  {id:'meeting',name:'Meeting notes',description:'Agenda, decisions and owners.',title:'Meeting notes – Date',html:'<h1>Meeting notes</h1><p><strong>Date:</strong> [Date]<br><strong>Attendees:</strong> [Names]<br><strong>Purpose:</strong> [Purpose]</p><h2>Agenda</h2><ol><li>Topic</li><li>Topic</li></ol><h2>Discussion</h2><p>Add concise notes here.</p><h2>Decisions</h2><ul><li>Decision and reason</li></ul><h2>Actions</h2><ul><li><strong>Owner:</strong> Action — Due date</li></ul>'},
  {id:'essay',name:'Essay',description:'Plan a structured argument.',title:'Essay title',html:'<h1>Essay title</h1><h2>Introduction</h2><p>Introduce the question, context and central argument.</p><h2>Main point one</h2><p>Claim, evidence and analysis.</p><h2>Main point two</h2><p>Claim, evidence and analysis.</p><h2>Counterargument</h2><p>Address a credible alternative interpretation.</p><h2>Conclusion</h2><p>Return to the argument and explain its significance.</p>'},
  {id:'proposal',name:'Business proposal',description:'Problem, solution, scope and next step.',title:'Business proposal',html:'<h1>Business proposal</h1><p><strong>Prepared for:</strong> [Client]<br><strong>Prepared by:</strong> [Name]<br><strong>Date:</strong> [Date]</p><h2>Executive summary</h2><p>Summarize the need, proposed outcome and value.</p><h2>Current challenge</h2><p>Describe the problem and its impact.</p><h2>Proposed solution</h2><p>Explain the approach and deliverables.</p><h2>Timeline</h2><ul><li>Phase one</li><li>Phase two</li></ul><h2>Investment</h2><p>[Price and terms]</p><h2>Next step</h2><p>[Clear call to action]</p>'},
  {id:'blog',name:'Blog post',description:'Headline, outline and publishing checklist.',title:'Blog post draft',html:'<h1>Working headline</h1><p><em>One-sentence promise to the reader.</em></p><h2>Introduction</h2><p>Open with the problem, observation or useful outcome.</p><h2>Key point one</h2><p>Add evidence and a concrete example.</p><h2>Key point two</h2><p>Add evidence and a concrete example.</p><h2>What to do next</h2><p>Give the reader a clear, practical next step.</p>'}
];
