import {loadDictionary} from './core/dictionary.js';
import {unscramble, exactAnagrams, findWords, wordleSearch} from './core/engine.js';
import {sanitizeLetters, sanitizePattern} from './core/filters.js';
const state={wordsByLength:new Map(),ready:false,results:[],visible:100};const $=id=>document.getElementById(id);
const resultList=$('results'),count=$('resultCount'),message=$('resultMessage'),showMore=$('showMoreButton'),copy=$('copyButton');
function clean(v,w=false){return(w?sanitizeLetters(v):sanitizePattern(v)).toLowerCase()}function setResults(items,label){state.results=items;state.visible=100;message.textContent=items.length?label:'No matches found. Try broader filters.';render()}function render(){resultList.textContent='';const f=document.createDocumentFragment();for(const item of state.results.slice(0,state.visible)){const li=document.createElement('li');li.className='word-result';li.innerHTML=`<strong>${item.word}</strong><span class="score">${item.meta || `${item.word.length} letters · ${item.score} pts`}</span>`;f.append(li)}resultList.append(f);count.textContent=state.results.length.toLocaleString();showMore.hidden=state.visible>=state.results.length;copy.disabled=!state.results.length}function ready(){if(state.ready)return true;message.textContent='The dictionary is still loading.';return false}
const bind=(id,fn)=>{const el=$(id);if(el)el.addEventListener('submit',fn)};
bind('unscramblerForm',e=>{e.preventDefault();if(!ready())return;const letters=clean($('unscrambleLetters').value,true);if(letters.length<2)return setResults([],'Enter at least two letters.');setResults(unscramble({letters,wordsByLength:state.wordsByLength,minLength:Number($('unscrambleMin').value),sort:$('unscrambleSort').value}),`Words made from ${letters.toUpperCase()}.`)});
bind('anagramForm',e=>{e.preventDefault();if(!ready())return;const letters=clean($('anagramLetters').value,true);if(letters.length<2)return setResults([],'Enter at least two letters.');setResults(exactAnagrams({letters,wordsByLength:state.wordsByLength,sort:$('anagramSort').value}),`Exact anagrams of ${letters.toUpperCase()}.`)});
bind('finderForm',e=>{e.preventDefault();if(!ready())return;setResults(findWords({wordsByLength:state.wordsByLength,length:Number($('finderLength').value)||0,pattern:clean($('finderPattern').value,true),starts:clean($('finderStarts').value),contains:clean($('finderContains').value),ends:clean($('finderEnds').value),excluded:clean($('finderExcluded').value),sort:'alpha'}),'Words matching your filters.')});
bind('wordleForm',e=>{e.preventDefault();if(!ready())return;setResults(wordleSearch({wordsByLength:state.wordsByLength,greens:clean($('wordleGreens').value,true),yellows:clean($('wordleYellows').value),grays:clean($('wordleGrays').value)}),'Five-letter candidates.')});
bind('crosswordForm',e=>{e.preventDefault();if(!ready())return;const length=Number($('crosswordLength').value)||0;let pattern=clean($('crosswordPattern').value,true);if(!pattern&&length)pattern='?'.repeat(length);if(pattern&&length&&pattern.length!==length)return setResults([],'The pattern length must match the answer length.');setResults(findWords({wordsByLength:state.wordsByLength,length:length||pattern.length,pattern,excluded:clean($('crosswordExcluded').value),sort:'alpha'}),'Possible crossword answers.');});
bind('scrabbleForm',e=>{e.preventDefault();if(!ready())return;const letters=clean($('scrabbleLetters').value,true);if(letters.length<2)return setResults([],'Enter at least two rack letters.');const filters={starts:clean($('scrabbleStarts').value),contains:clean($('scrabbleContains').value),ends:clean($('scrabbleEnds').value)};setResults(unscramble({letters,wordsByLength:state.wordsByLength,minLength:Number($('scrabbleMin').value)||2,filters,sort:$('scrabbleSort').value}),`Playable words from ${letters.toUpperCase()}, ranked by Scrabble tile value.`);});

bind('randomForm',e=>{e.preventDefault();if(!ready())return;const length=Number($('randomLength').value)||0;const countWanted=Math.min(50,Math.max(1,Number($('randomCount').value)||10));const starts=clean($('randomStarts').value);const contains=clean($('randomContains').value);const pool=[];const lengths=length?[length]:[...state.wordsByLength.keys()];for(const len of lengths){for(const word of state.wordsByLength.get(len)||[]){if(starts&&!word.startsWith(starts))continue;if(contains&&!word.includes(contains))continue;if(word.length<2||word.length>15)continue;pool.push(word)}}for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}const items=pool.slice(0,countWanted).map(word=>({word,score:0,meta:`${word.length} letters · random pick`}));setResults(items,`Generated ${items.length} random word${items.length===1?'':'s'} from ${pool.length.toLocaleString()} matching entries.`);});

bind('rhymeForm',e=>{e.preventDefault();if(!ready())return;const source=clean($('rhymeWord').value);if(source.length<3)return setResults([],'Enter a word with at least three letters.');const depth=Math.min(source.length,Math.max(2,Number($('rhymeDepth').value)||3));const ending=source.slice(-depth);const maxLength=Number($('rhymeMaxLength').value)||0;const items=[];for(const [len,words] of state.wordsByLength){if(maxLength&&len>maxLength)continue;for(const word of words){if(word===source||!word.endsWith(ending))continue;items.push({word,score:0,meta:`${word.length} letters · ends in ${ending.toUpperCase()}`});if(items.length>=5000)break}if(items.length>=5000)break}items.sort((a,b)=>Math.abs(a.word.length-source.length)-Math.abs(b.word.length-source.length)||a.word.localeCompare(b.word));setResults(items,`Words sharing the ending ${ending.toUpperCase()} with ${source.toUpperCase()}.`);});
showMore.addEventListener('click',()=>{state.visible+=100;render()});copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(state.results.map(x=>x.word).join('\n'));copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy all',1200)}catch{message.textContent='Copy failed. Select the words manually.'}});
const toggle=$('themeToggle');toggle.addEventListener('click',()=>{const d=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=d?'dark':'light';localStorage.setItem('lt-theme',d?'dark':'light');toggle.textContent=d?'Light mode':'Dark mode'});if(localStorage.getItem('lt-theme')==='dark'){document.documentElement.dataset.theme='dark';toggle.textContent='Light mode'}
try{const d=await loadDictionary('../words.txt');state.wordsByLength=d.wordsByLength;state.ready=true;message.textContent=`${d.total.toLocaleString()} words ready. Enter your clues and search.`}catch(err){message.textContent='Dictionary unavailable. Please refresh the page.';console.error(err)}
