import {loadDictionary} from './core/dictionary.js';
import {unscramble, exactAnagrams, findWords, wordleSearch} from './core/engine.js';
import {sanitizeLetters, sanitizePattern} from './core/filters.js';
const state={wordsByLength:new Map(),ready:false,results:[],visible:100};const $=id=>document.getElementById(id);
const resultList=$('results'),count=$('resultCount'),message=$('resultMessage'),showMore=$('showMoreButton'),copy=$('copyButton');
function clean(v,w=false){return(w?sanitizeLetters(v):sanitizePattern(v)).toLowerCase()}function setResults(items,label){state.results=items;state.visible=100;message.textContent=items.length?label:'No matches found. Try broader filters.';render()}function render(){resultList.textContent='';const f=document.createDocumentFragment();for(const item of state.results.slice(0,state.visible)){const li=document.createElement('li');li.className='word-result';li.innerHTML=`<strong>${item.word}</strong><span class="score">${item.word.length} letters · ${item.score} pts</span>`;f.append(li)}resultList.append(f);count.textContent=state.results.length.toLocaleString();showMore.hidden=state.visible>=state.results.length;copy.disabled=!state.results.length}function ready(){if(state.ready)return true;message.textContent='The dictionary is still loading.';return false}
const bind=(id,fn)=>{const el=$(id);if(el)el.addEventListener('submit',fn)};
bind('unscramblerForm',e=>{e.preventDefault();if(!ready())return;const letters=clean($('unscrambleLetters').value,true);if(letters.length<2)return setResults([],'Enter at least two letters.');setResults(unscramble({letters,wordsByLength:state.wordsByLength,minLength:Number($('unscrambleMin').value),sort:$('unscrambleSort').value}),`Words made from ${letters.toUpperCase()}.`)});
bind('anagramForm',e=>{e.preventDefault();if(!ready())return;const letters=clean($('anagramLetters').value,true);if(letters.length<2)return setResults([],'Enter at least two letters.');setResults(exactAnagrams({letters,wordsByLength:state.wordsByLength,sort:$('anagramSort').value}),`Exact anagrams of ${letters.toUpperCase()}.`)});
bind('finderForm',e=>{e.preventDefault();if(!ready())return;setResults(findWords({wordsByLength:state.wordsByLength,length:Number($('finderLength').value)||0,pattern:clean($('finderPattern').value,true),starts:clean($('finderStarts').value),contains:clean($('finderContains').value),ends:clean($('finderEnds').value),excluded:clean($('finderExcluded').value),sort:'alpha'}),'Words matching your filters.')});
bind('wordleForm',e=>{e.preventDefault();if(!ready())return;setResults(wordleSearch({wordsByLength:state.wordsByLength,greens:clean($('wordleGreens').value,true),yellows:clean($('wordleYellows').value),grays:clean($('wordleGrays').value)}),'Five-letter candidates.')});
showMore.addEventListener('click',()=>{state.visible+=100;render()});copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(state.results.map(x=>x.word).join('\n'));copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy all',1200)}catch{message.textContent='Copy failed. Select the words manually.'}});
const toggle=$('themeToggle');toggle.addEventListener('click',()=>{const d=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=d?'dark':'light';localStorage.setItem('lt-theme',d?'dark':'light');toggle.textContent=d?'Light mode':'Dark mode'});if(localStorage.getItem('lt-theme')==='dark'){document.documentElement.dataset.theme='dark';toggle.textContent='Light mode'}
try{const d=await loadDictionary('../words.txt');state.wordsByLength=d.wordsByLength;state.ready=true;message.textContent=`${d.total.toLocaleString()} words ready. Enter your clues and search.`}catch(err){message.textContent='Dictionary unavailable. Please refresh the page.';console.error(err)}
