(()=>{const map={
"/word-counter/":[["/character-counter/","Character Counter","Check characters with and without spaces."],["/reading-time-calculator/","Reading Time","Estimate how long the text takes to read."],["/text-analyzer/","Text Analyzer","See all text statistics together."]],
"/character-counter/":[["/word-counter/","Word Counter","Count words, sentences and paragraphs."],["/letter-counter/","Letter Counter","Count letters only."],["/text-analyzer/","Text Analyzer","See all text statistics together."]],
"/text-cleaner/":[["/remove-extra-spaces/","Remove Extra Spaces","Focus on repeated spacing."],["/remove-line-breaks/","Remove Line Breaks","Join unwanted line breaks."],["/case-converter/","Case Converter","Change capitalization after cleaning."]],
"/word-frequency-counter/":[["/text-analyzer/","Text Analyzer","See full text statistics."],["/word-counter/","Word Counter","Check core length metrics."],["/text-cleaner/","Text Cleaner","Clean the source text first."]],
"/reading-time-calculator/":[["/speaking-time-calculator/","Speaking Time","Estimate speech duration."],["/word-counter/","Word Counter","Check the exact word count."],["/text-analyzer/","Text Analyzer","See all text statistics."]],
"/speaking-time-calculator/":[["/reading-time-calculator/","Reading Time","Estimate reading duration."],["/word-counter/","Word Counter","Check the exact word count."],["/text-analyzer/","Text Analyzer","See all text statistics."]],
"/line-counter/":[["/paragraph-counter/","Paragraph Counter","Count paragraph blocks."],["/remove-empty-lines/","Remove Empty Lines","Delete blank lines."],["/remove-line-breaks/","Remove Line Breaks","Join unwanted breaks."]],
"/case-converter/":[["/text-cleaner/","Text Cleaner","Clean text before formatting."],["/find-and-replace/","Find & Replace","Replace words or phrases."],["/slug-generator/","Slug Generator","Turn text into a URL slug."]]
};const items=map[location.pathname];if(!items||document.querySelector('[data-auto-related]'))return;const main=document.querySelector('main');if(!main)return;const s=document.createElement('section');s.className='content-section shell';s.dataset.autoRelated='1';s.innerHTML='<div class="section-heading"><p class="eyebrow">Related tools</p><h2>Useful next steps</h2></div><div class="tool-card-grid">'+items.map(x=>'<a class="tool-card" data-related-tool href="'+x[0]+'"><h3>'+x[1]+'</h3><p>'+x[2]+'</p><b>Open tool →</b></a>').join('')+'</div>';main.appendChild(s)})();